# Generated by Django 4.2.6 on 2023-11-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='applications',
            name='Status',
            field=models.CharField(blank=True, default='Новая', max_length=16, verbose_name='Статус'),
        ),
    ]
