# Generated by Django 4.2.7 on 2023-11-02 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_alter_applications_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 19, 54, 41, 411345), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='applications',
            name='time_create',
            field=models.TimeField(default=datetime.datetime(2023, 11, 2, 19, 54, 41, 411345), verbose_name='Время создания'),
        ),
    ]
